package com.vivekpanchal.newshub.database;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;

@Entity(tableName = "news_headlines")
public class NewsHeadlineEntity {

    @PrimaryKey(autoGenerate = true)
    private int id;
    @ColumnInfo(name = "news_headline")
    private String headline;
    private String date;
    @ColumnInfo(name = "image_url")
    private String imageUrl;
    @ColumnInfo(name = "author_name")
    private String authorName;
    private String description;
    @ColumnInfo(name = "news_source")
    private String newsSource;
    @ColumnInfo(name = "news_url")
    private String newsUrl;

    // Note: One of the limitation of Room is that it can have only one constructor and we have two.
    // So ignoring the first one since it is to be used by us and id is autoGenerated so Room will not require it.

    @Ignore
    public NewsHeadlineEntity(String headline, String date, String imageUrl, String authorName,
                              String description, String newsSource, String newsUrl) {
        this.headline = headline;
        this.date = date;
        this.imageUrl = imageUrl;
        this.authorName = authorName;
        this.description = description;
        this.newsSource = newsSource;
        this.newsUrl = newsUrl;
    }

    public NewsHeadlineEntity(int id, String headline, String date, String imageUrl, String authorName,
                              String description, String newsSource, String newsUrl){
        this.id = id;
        this.headline = headline;
        this.date = date;
        this.imageUrl = imageUrl;
        this.authorName = authorName;
        this.description = description;
        this.newsSource = newsSource;
        this.newsUrl = newsUrl;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getHeadline() {
        return headline;
    }

    public void setHeadline(String headline) {
        this.headline = headline;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getAuthorName() {
        return authorName;
    }

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getNewsSource() {
        return newsSource;
    }

    public void setNewsSource(String newsSource) {
        this.newsSource = newsSource;
    }

    public String getNewsUrl() {
        return newsUrl;
    }

    public void setNewsUrl(String newsUrl) {
        this.newsUrl = newsUrl;
    }
}
